env: standard
runtime: nodejs12
service: default

env_variables:
  NEXT_PUBLIC_TEST_VAR: test_this_string

instance_class: F2

handlers:
  - url: /.*
    secure: always
    script: auto

inbound_services:
  - warmup
resources:

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 100
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: 2000ms
  max_pending_latency: automatic
