env: standard
runtime: nodejs10
service: default

instance_class: F4

handlers:
  - url: /.*
    secure: always
    script: auto

inbound_services:
  - warmup

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 100
  min_idle_instances: 2
  max_idle_instances: automatic
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20
