env: standard
runtime: nodejs10
service: default

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 100
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

inbound_services:
  - warmup
